<a href="https://colab.research.google.com/github/SrijaC2/Sentiment_Analysis/blob/main/Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/Reddit_Data.csv")
df

clean_comment  category
0       family mormon have never tried explain them t...         1
1      buddhism has very much lot compatible with chr...         1
2      seriously don say thing first all they won get...        -1
3      what you have learned yours and only yours wha...         0
4      for your own benefit you may want read living ...         1
...                                                  ...       ...
37244                                              jesus         0
37245  kya bhai pure saal chutiya banaya modi aur jab...         1
37246              downvote karna tha par upvote hogaya          0
37247                                         haha nice          1
37248             facebook itself now working bjp’ cell          0

[37249 rows x 2 columns]

In [ ]:
df['clean_comment']=df['clean_comment'].str.lower()
df

clean_comment  category
0       family mormon have never tried explain them t...         1
1      buddhism has very much lot compatible with chr...         1
2      seriously don say thing first all they won get...        -1
3      what you have learned yours and only yours wha...         0
4      for your own benefit you may want read living ...         1
...                                                  ...       ...
37244                                              jesus         0
37245  kya bhai pure saal chutiya banaya modi aur jab...         1
37246              downvote karna tha par upvote hogaya          0
37247                                         haha nice          1
37248             facebook itself now working bjp’ cell          0

[37249 rows x 2 columns]

In [ ]:
df=df[(df['category']==1) | (df['category']==-1)]
df

clean_comment  category
0       family mormon have never tried explain them t...         1
1      buddhism has very much lot compatible with chr...         1
2      seriously don say thing first all they won get...        -1
4      for your own benefit you may want read living ...         1
5      you should all sit down together and watch the...        -1
...                                                  ...       ...
37236   fan modi but some the best people ever met li...         1
37240  nice same shock laga effect the night demoneti...         1
37243  this agree why push make other nations either ...        -1
37245  kya bhai pure saal chutiya banaya modi aur jab...         1
37247                                         haha nice          1

[24107 rows x 2 columns]

In [ ]:
import re
def remove_html_tags(text):
  pattern=re.compile('<.*?>')
  return pattern.sub(r'',text)


In [ ]:
df['clean_comment']=df['clean_comment'].apply(remove_html_tags)
df.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


clean_comment  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
4  for your own benefit you may want read living ...         1
5  you should all sit down together and watch the...        -1

In [ ]:
def remove_url(text):
  pattern=re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'',text)

In [ ]:
df['clean_comment']=df['clean_comment'].apply(remove_url)
df.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


clean_comment  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
4  for your own benefit you may want read living ...         1
5  you should all sit down together and watch the...        -1

In [ ]:
import string
exc=string.punctuation
exc

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
def remove_punc1(text):
  return text.translate(str.maketrans('', '',exc))

In [ ]:
df['clean_comment']=df['clean_comment'].apply(remove_punc1)
df.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


clean_comment  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
4  for your own benefit you may want read living ...         1
5  you should all sit down together and watch the...        -1

In [ ]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
def stem_words(text):
  return " ".join([ps.stem(word) for word in text.split()])

In [ ]:
df['clean_comment']=df['clean_comment'].apply(stem_words)
df.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


clean_comment  category
0  famili mormon have never tri explain them they...         1
1  buddhism ha veri much lot compat with christia...         1
2  serious don say thing first all they won get i...        -1
4  for your own benefit you may want read live bu...         1
5  you should all sit down togeth and watch the s...        -1

In [ ]:
df['category'].value_counts()

 1    15830
-1     8277
Name: category, dtype: int64

In [ ]:
x=df['clean_comment'].values
y=df['category'].values


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33, random_state=42)

In [ ]:
x_train.shape

(16151,)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english')

In [ ]:
x_train_vect=cv.fit_transform(x_train)
x_test_vect=cv.transform(x_test)
x_train_vect

<16151x26428 sparse matrix of type '<class 'numpy.int64'>'
	with 342465 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()
nb.fit(x_train_vect,y_train)

MultinomialNB()

In [ ]:
y_pred=nb.predict(x_test_vect)

In [ ]:
y_pred

array([-1,  1,  1, ...,  1,  1, -1])

In [ ]:
y_test

array([-1,  1,  1, ...,  1, -1, -1])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.7645801910507792

In [ ]:
confusion_matrix(y_test,y_pred)

array([[1219, 1504],
       [ 369, 4864]])